"""Section map for the grade-11 site.

Each پودمان is cut by topic, not by printed page. Book pages listed here
are the inclusive book-page numbers already marked in the markdown.
"""

from __future__ import annotations

MODULES = [
    {
        "id": "open",
        "fa": "شروع کتاب",
        "en": "Opening",
        "blurb_fa": "جلد، مجوز آزاد کتاب، و فهرست.",
        "blurb_en": "Cover, the book's free license, and the contents.",
        "home": False,
    },
    {
        "id": "p1",
        "fa": "پودمان ۱: برنامه‌نویسی پایتون",
        "en": "Module 1: Python programming",
        "blurb_fa": "مدل‌سازی داده، توابع و ماژول‌ها.",
        "blurb_en": "Data modeling, functions, and modules.",
        "home": True,
    },
    {
        "id": "p2",
        "fa": "پودمان ۲: صفحات وب ایستا",
        "en": "Module 2: Static web pages",
        "blurb_fa": "ساختار صفحه با HTML و ظاهر با CSS.",
        "blurb_en": "Page structure with HTML and appearance with CSS.",
        "home": True,
    },
    {
        "id": "p3",
        "fa": "پودمان ۳: صفحات وب تعاملی",
        "en": "Module 3: Interactive web pages",
        "blurb_fa": "بوت‌استرپ و جاوااسکریپت.",
        "blurb_en": "Bootstrap and JavaScript.",
        "home": True,
    },
    {
        "id": "p4",
        "fa": "پودمان ۴: توسعه وب پایتون",
        "en": "Module 4: Python for the web",
        "blurb_fa": "تولید و توسعه برنامه شیءگرا.",
        "blurb_en": "Building and extending object-oriented programs.",
        "home": True,
    },
    {
        "id": "p5",
        "fa": "پودمان ۵: برنامه‌نویسی جنگو",
        "en": "Module 5: Django",
        "blurb_fa": "ایجاد و توسعه وب‌اپلیکیشن.",
        "blurb_en": "Creating and developing a web application.",
        "home": True,
    },
    {
        "id": "back",
        "fa": "پایان کتاب",
        "en": "Back of the book",
        "blurb_fa": "منابعی که کتاب معرفی کرده است.",
        "blurb_en": "Sources listed in the book.",
        "home": False,
    },
]


def S(id, module, unit_fa, unit_en, file, start, end, fa, en, ex_fa, ex_en, link=None):
    return {
        "id": id,
        "module": module,
        "unit_fa": unit_fa,
        "unit_en": unit_en,
        "file": file,
        "start": start,
        "end": end,
        "fa": fa,
        "en": en,
        "ex_fa": ex_fa,
        "ex_en": ex_en,
        "link": link,
    }


PY = "https://docs.python.org/3/tutorial/"
MDN_HTML = "https://developer.mozilla.org/en-US/docs/Learn/HTML"
MDN_CSS = "https://developer.mozilla.org/en-US/docs/Learn/CSS"
MDN_JS = "https://developer.mozilla.org/en-US/docs/Learn/JavaScript"
BS = "https://getbootstrap.com/docs/5.3/getting-started/introduction/"
DJ = "https://docs.djangoproject.com/en/stable/intro/tutorial01/"

SECTIONS = [
    S("toc", "open", "فهرست", "Contents", "00-toc.md", 4, 6,
      "فهرست", "Contents",
      ["از فهرست، شماره صفحه شروع هر پنج پودمان را بنویس.",
       "برای هفته آینده یک پودمان را انتخاب کن و بگو کدام واحد یادگیری‌اش را اول می‌خوانی و چرا."],
      ["From the contents, write the starting page of each of the five modules.",
       "Pick one module for next week. Which learning unit will you read first, and why?"],
      None),

    S("p1-intro", "p1", "معرفی پودمان", "Module introduction",
      "01-poodman-1-python/00-intro.md", 1, 1,
      "معرفی پودمان پایتون", "Introducing the Python module",
      ["به زبان خودت بنویس این پودمان در پایان سال باید چه کاری را بتوانی انجام بدهی.",
       "یک برنامه کوچک که دوست داری با پایتون بسازی نام ببر و بگو کدام بخش این پودمان به آن مربوط است."],
      ["In your own words, write what you should be able to do at the end of this module.",
       "Name one small program you would like to build in Python, and which part of this module it depends on."],
      (PY, "آموزش رسمی پایتون", "Official Python tutorial")),

    S("p1-python", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 2, 7,
      "پایتون و محیط برنامه‌نویسی", "Python and the programming environment",
      ["در IDLE یک فایل بساز که نام تو و پایه تحصیلی‌ات را در دو خط چاپ کند. فایل را ذخیره و اجرا کن.",
       "یک متن چندخطی با سه کوتیشن بنویس که قوانین کلاس کامپیوتر را نشان بدهد. بگو تورفتگی در پایتون چه فرقی با فاصله تزئینی دارد."],
      ["In IDLE, save and run a file that prints your name and grade on two lines.",
       "Print a multi-line notice with triple quotes. Explain how indentation in Python differs from decoration space."],
      (PY + "introduction.html", "شروع آموزش پایتون", "Python tutorial: introduction")),

    S("p1-vars", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 8, 12,
      "متغیرها، نوع داده و عملگرها", "Variables, types, and operators",
      ["برای یک کالا سه متغیر بساز: نام (رشته)، قیمت (عدد صحیح) و تخفیف (عدد اعشاری). نوع هر کدام را با برنامه نشان بده.",
       "دو رشته را با + به هم بچسبان و همان عملگر را روی دو عدد هم امتحان کن. خروجی هر دو را بنویس و فرق را توضیح بده."],
      ["Create three variables for a product: name (string), price (integer), and discount (float). Show the type of each.",
       "Join two strings with +, then use + on two numbers. Write both outputs and explain the difference."],
      (PY + "introduction.html#an-informal-introduction-to-python", "عدد و رشته در پایتون", "Numbers and strings in Python")),

    S("p1-cast", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 13, 15,
      "ورودی و تبدیل نوع", "Input and type casting",
      ["برنامه‌ای بنویس که قیمت و تعداد را با input بگیرد و مبلغ کل را عددی حساب کند. اگر تبدیل نکنی چه خطایی می‌گیری؟",
       "سن کاربر را رشته بگیر، به عدد صحیح تبدیل کن و بگو آیا به ۱۵ سال رسیده است یا نه."],
      ["Write a program that reads a price and a quantity with input and calculates the total as a number. What error do you get if you skip the conversion?",
       "Read an age as text, convert it to an integer, and report whether the person is 15 or older."],
      (PY + "inputoutput.html", "ورودی و خروجی", "Input and output")),

    S("p1-lists", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 16, 21,
      "لیست‌ها", "Lists",
      ["یک لیست از پنج میان‌بر غذایی بساز. موردی را در جای مشخص درج کن، یکی را با مقدار حذف کن، و آخری را با pop بردار. بعد از هر تغییر لیست را چاپ کن.",
       "عنصر اول و سوم لیست را با ایندکس عوض کن. اگر ایندکسی بزرگ‌تر از طول لیست بخواهی، چه اتفاقی می‌افتد؟"],
      ["Build a list of five snacks. Insert one at a chosen index, remove one by value, and pop the last item. Print the list after each change.",
       "Swap the first and third items by index. What happens if you ask for an index past the end of the list?"],
      (PY + "introduction.html#lists", "لیست‌ها در آموزش پایتون", "Lists in the Python tutorial")),

    S("p1-if", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 22, 26,
      "شرط‌های ساده", "Simple conditions",
      ["برنامه‌ای بنویس که نمره را بگیرد: ۱۸ به بالا «عالی»، زیر ۱۰ «نیاز به تمرین»، و بین آن‌ها «قابل قبول».",
       "با عملگرهای and و or بررسی کن که رمز هم حداقل ۸ حرف باشد و هم عدد داشته باشد. دو مثال درست و یک مثال نادرست اجرا کن."],
      ["Read a score. Print «excellent» for 18 or above, «needs practice» below 10, and «acceptable» in between.",
       "Use and and or to require a password of at least 8 characters that also contains a digit. Run two valid examples and one invalid one."],
      (PY + "controlflow.html#if-statements", "دستور if", "if statements")),

    S("p1-elif", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 27, 32,
      "if، elif و else", "if, elif, and else",
      ["منوی غذا با سه گزینه بنویس. اگر گزینه نامعتبر بود پیام خطا بده. چرا یک زنجیره if-elif-else اینجا از چند if جدا بهتر است؟",
       "سطح بازی را از ورودی بگیر (آسان، متوسط، سخت) و برای هر کدام یک جمله متفاوت چاپ کن."],
      ["Write a three-item food menu. Print an error for an unknown choice. Why is one if-elif-else chain better here than separate if statements?",
       "Read a game level (easy, medium, hard) and print a different sentence for each."],
      (PY + "controlflow.html#if-statements", "شاخه‌های elif", "elif branches")),

    S("p1-for", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 33, 39,
      "حلقه for و range", "The for loop and range",
      ["نام چهار کالا را در یک لیست بگذار و با for چاپ کن. اگر به کالای «soup» رسیدی یک جمله اضافه چاپ کن و با continue به بعدی برو.",
       "با range جمع عددهای ۱ تا ۲۰ را حساب کن. یک بار range را با شروع و گام غیر از ۱ هم امتحان کن و خروجی را بنویس."],
      ["Store four product names and print them with for. When you reach «soup», print an extra sentence and continue to the next item.",
       "Use range to add the numbers from 1 to 20. Then try a start and step other than 1, and write the output."],
      (PY + "controlflow.html#for-statements", "حلقه for", "for statements")),

    S("p1-while", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 40, 45,
      "حلقه while و کنترل حلقه", "The while loop and loop control",
      ["با while از کاربر عدد بگیر و مربعش را چاپ کن تا وقتی که صفر وارد کند. اگر ورودی غیرعددی بود چه باید بکنی؟",
       "یک لیست خالی بساز و تا وقتی کاربر کلمه «پایان» را ننوشته، نام مهمان را به لیست اضافه کن. break را کجا لازم داری؟"],
      ["With while, read a number and print its square until the user enters 0. What should you do if the input is not a number?",
       "Start from an empty list and keep adding guest names until the user types «end». Where do you need break?"],
      (PY + "introduction.html#first-steps-towards-programming", "حلقه while", "while loops")),

    S("p1-assess-data", "p1", "مدل‌سازی داده", "Data modeling",
      "01-poodman-1-python/01-data-modeling.md", 46, 47,
      "ارزشیابی مدل‌سازی داده", "Data-modeling assessment",
      ["یکی از سؤال‌های ارزشیابی کتاب را بدون نگاه به پاسخ بنویس و حل کن. بعد راه‌حلت را با معیار شایستگی همان صفحه مقایسه کن.",
       "برنامه‌ای یک‌صفحه‌ای بساز که لیست خرید را بسازد، یک قلم اضافه کند، یک قلم حذف کند، و با یک شرط بگوید آیا بودجه کافی است."],
      ["Copy one assessment question from the book and solve it without looking at a sample answer. Then compare your solution with the competency on that page.",
       "Build a one-page program that creates a shopping list, adds an item, removes an item, and uses a condition to say whether the budget is enough."],
      None),

    S("p1-sets", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 48, 51,
      "مجموعه (set)", "Sets",
      ["نام درس‌های دو دانش‌آموز را در دو مجموعه بریز. درس‌های مشترک و درس‌هایی که فقط نفر اول دارد را چاپ کن.",
       "یک عضو تکراری به مجموعه اضافه کن و طول مجموعه را قبل و بعد نشان بده. چرا تعداد عوض نشد؟"],
      ["Put two students' subjects in two sets. Print the subjects they share and the subjects only the first student has.",
       "Add a duplicate member to a set and show the length before and after. Why did the count stay the same?"],
      (PY + "datastructures.html#sets", "مجموعه‌ها", "Sets")),

    S("p1-dict", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 52, 56,
      "دیکشنری", "Dictionaries",
      ["دفترچه تلفن سه نفر را با دیکشنری بساز. یک شماره را عوض کن، یک نفر را با pop حذف کن، و وجود یک نام را با in بررسی کن.",
       "یک دیکشنری خالی بساز و از کاربر سه کلید و مقدار بگیر. اگر کلید تکراری وارد شد، مقدار قبلی چه می‌شود؟"],
      ["Build a phone book of three people. Change one number, remove one person with pop, and test a name with in.",
       "Start from an empty dictionary and read three keys and values. What happens to the old value if the key is repeated?"],
      (PY + "datastructures.html#dictionaries", "دیکشنری‌ها", "Dictionaries")),

    S("p1-quiz", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 57, 59,
      "پروژه بازی Quiz", "Quiz game project",
      ["همان بازی کتاب را با سه سؤال از درس خودتان تمام کن. امتیاز را در یک متغیر نگه دار و در پایان چاپ کن.",
       "منوی بازی را طوری بنویس که گزینه خروج واقعاً حلقه را تمام کند، نه اینکه فقط یک پیام چاپ شود."],
      ["Finish the book's quiz with three questions from your own course. Keep the score in a variable and print it at the end.",
       "Write the game menu so the quit option actually ends the loop, rather than only printing a message."],
      None),

    S("p1-tuple", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 60, 61,
      "تاپل", "Tuples",
      ["یک تاپل برای نام کاربری مدیران بساز و سعی کن عضو دوم را عوض کنی. متن خطا را در دفترت بنویس.",
       "بگو چه وقت تاپل را به لیست ترجیح می‌دهی. یک مثال از داده‌ای که نباید در طول برنامه عوض شود بیاور."],
      ["Create a tuple of administrator usernames and try to change the second item. Copy the error into your notes.",
       "Say when you would choose a tuple over a list. Give one example of data that should not change during the program."],
      (PY + "datastructures.html#tuples-and-sequences", "تاپل‌ها", "Tuples")),

    S("p1-func", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 62, 69,
      "تعریف تابع، پارامتر و return", "Defining functions, parameters, and return",
      ["تابعی بنویس که نام فروشگاه را چاپ کند، و تابع دیگری که دو قیمت را بگیرد و گران‌تر را برگرداند. نتیجه return را در یک متغیر ذخیره کن.",
       "تابعی با دو پارامتر پیش‌فرض برای پیام خوشامد بساز. یک بار بدون آرگومان و یک بار با آرگومان صدایش کن."],
      ["Write a function that prints a shop name, and another that takes two prices and returns the higher one. Store the returned value in a variable.",
       "Write a greeting function with two default parameters. Call it once with no arguments and once with arguments."],
      (PY + "controlflow.html#defining-functions", "تعریف تابع", "Defining functions")),

    S("p1-func-more", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 70, 73,
      "تمرین تابع و مرتب‌سازی", "Function practice and sorting",
      ["تابعی بنویس که لیست نام‌ها را بگیرد و تعداد نام‌های طولانی‌تر از ۴ حرف را برگرداند. با یک لیست واقعی امتحان کن.",
       "رشته‌ای از حروف به‌هم‌ریخته را با sorted مرتب کن و بگو خروجی sorted لیست است یا همان رشته."],
      ["Write a function that takes a list of names and returns how many are longer than 4 letters. Try it on a real list.",
       "Sort a scrambled string with sorted, and say whether the result is a list or the original string."],
      (PY + "controlflow.html#more-on-defining-functions", "ادامه تابع‌ها", "More on defining functions")),

    S("p1-modules", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 74, 79,
      "ماژول‌ها و تفاوت تابع و متد", "Modules, and functions versus methods",
      ["با ماژول random از یک لیست پیام انگیزشی هر بار یکی را چاپ کن. سپس جذر ۲۵ را یک بار با math.sqrt و یک بار بعد از import مستقیم حساب کن.",
       "روی یک رشته متد split را صدا بزن و همان کار را با یک تابع خودت مقایسه کن. در دو سطر بگو تابع و متد چه فرقی دارند."],
      ["Use random to print one motivational message from a list on each run. Then compute the square root of 25 once with math.sqrt and once after a direct import.",
       "Call split on a string, and compare it with a function you write yourself. In two lines, state how a function differs from a method."],
      (PY + "modules.html", "ماژول‌ها", "Modules")),

    S("p1-assess-func", "p1", "توابع و ماژول‌ها", "Functions and modules",
      "01-poodman-1-python/02-functions-and-modules.md", 80, 82,
      "ارزشیابی توابع و ماژول‌ها", "Functions and modules assessment",
      ["تابع خوشامدگویی و تابع جمع دو عدد را که در ارزشیابی آمده جداگانه بنویس و هر کدام را دو بار با داده مختلف صدا بزن.",
       "یک ماژول کوچک به نام shop.py بساز که یک تابع تخفیف داشته باشد، و از برنامه اصلی import کن."],
      ["Write the greeting function and the two-number function from the assessment separately, and call each twice with different data.",
       "Create a small module named shop.py with a discount function, and import it from the main program."],
      None),

    S("p2-intro", "p2", "معرفی پودمان", "Module introduction",
      "02-poodman-2-static-web/00-intro.md", 83, 83,
      "معرفی پودمان صفحات ایستا", "Introducing static web pages",
      ["فرق صفحه‌ای که فقط HTML و CSS دارد با صفحه‌ای که به کلیک کاربر جواب می‌دهد را در سه سطر بنویس.",
       "یک سایت مدرسه‌ای نام ببر و بگو کدام بخش‌هایش را با این پودمان می‌توان ساخت."],
      ["In three lines, contrast a page that has only HTML and CSS with a page that answers a user's click.",
       "Name a school website and say which parts of it this module can build."],
      (MDN_HTML, "آموزش HTML در MDN", "MDN: Learn HTML")),

    S("p2-web", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 84, 85,
      "وب چگونه کار می‌کند", "How the web works",
      ["مسیر یک درخواست را از مرورگر خودت تا رسیدن صفحه بنویس: مرورگر، آدرس، سرور، پاسخ.",
       "بگو فایل HTML روی هاست چه فرقی با همان فایل روی رایانه کلاس دارد."],
      ["Write the path of a request from your browser to the finished page: browser, address, server, response.",
       "Explain how an HTML file on a host differs from the same file on the lab computer."],
      ("https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work",
       "اینترنت چگونه کار می‌کند", "How the internet works")),

    S("p2-concepts", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 86, 92,
      "مفاهیم طراحی وب و نقشه سایت", "Web-design concepts and the site map",
      ["برای یک سایت سه صفحه‌ای کتابخانه مدرسه، هدف سایت و سه نیازمندی فنی بنویس. بعد نقشه سایت را روی کاغذ بکش.",
       "طراحی واکنش‌گرا را با یک مثال از عرض موبایل و عرض رایانه توضیح بده، بدون نوشتن کد."],
      ["For a three-page school-library site, write the goal and three technical requirements. Then sketch the site map.",
       "Explain responsive design with one phone-width example and one desktop-width example, without writing code."],
      ("https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web",
       "شروع ساخت وب", "Getting started with the web")),

    S("p2-tags", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 93, 97,
      "اولین صفحه HTML", "A first HTML page",
      ["یک صفحه با doctype، عنوان و یک پاراگراف بساز و در مرورگر باز کن. عنوان زبانه مرورگر را با عنوان داخل صفحه یکی نگذار تا فرق را ببینی.",
       "همان صفحه را یک بار با باز کردن فایل و یک بار با Go Live ببین. کدام را برای کار کلاسی ترجیح می‌دهی و چرا؟"],
      ["Build a page with a doctype, a title, and one paragraph, and open it in a browser. Make the tab title differ from the heading on the page so you can see the difference.",
       "View the same page by opening the file and with Go Live. Which do you prefer for class work, and why?"],
      ("https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started",
       "شروع HTML", "Getting started with HTML")),

    S("p2-text", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 98, 103,
      "متن، لیست و پیوند", "Text, lists, and links",
      ["صفحه‌ای با یک عنوان، یک متن تأکیدشده، یک لیست از کتاب‌های رشته، و یک پیوند به پایین همان صفحه (با id) بساز.",
       "پیوند به یک سایت بیرونی را با target مناسب باز کن و بگو چرا مقصد داخل صفحه با مقصد بیرون فرق دارد."],
      ["Build a page with a heading, emphasized text, a list of books in your field, and a link to the bottom of the same page using an id.",
       "Open an external link with a suitable target, and explain how an in-page destination differs from an outside one."],
      ("https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals",
       "مبانی متن HTML", "HTML text fundamentals")),

    S("p2-img", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 104, 105,
      "تصویر در صفحه", "Images on the page",
      ["یک تصویر را با width و height مشخص در صفحه بگذار و متن alt را طوری بنویس که اگر تصویر باز نشد، معنی‌اش معلوم باشد.",
       "اگر مسیر تصویر اشتباه باشد صفحه چه نشان می‌دهد؟ مسیر را عمداً خراب کن و نتیجه را یادداشت کن، بعد درستش کن."],
      ["Place an image with a set width and height, and write alt text that still makes sense if the image fails to load.",
       "What does the page show if the image path is wrong? Break the path on purpose, note the result, then fix it."],
      ("https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML",
       "تصویر در HTML", "Images in HTML")),

    S("p2-forms", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 106, 110,
      "فرم‌ها", "Forms",
      ["فرم عضویت با نام، رمز، یک گروه دکمه رادیویی و دکمه ارسال بساز. name دکمه‌های رادیویی را یکسان بگذار و بگو چرا.",
       "جدول مقایسه روش‌های ارسال فرم را در دو سطر به زبان خودت جمع کن: چه داده‌ای با کدام روش مناسب‌تر است؟"],
      ["Build a signup form with a name, a password, one radio group, and a submit button. Give the radio buttons the same name, and say why.",
       "Summarize the book's comparison of form-sending methods in two lines: which kind of data fits which method?"],
      ("https://developer.mozilla.org/en-US/docs/Learn/Forms",
       "فرم‌های وب", "Web forms")),

    S("p2-semantic", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 111, 113,
      "عناصر معنایی", "Semantic elements",
      ["یک صفحه مقاله را با header، main، section و aside بچین. کنارش همان طرح را فقط با div بنویس و بگو کدام را برای یک صفحه واقعی انتخاب می‌کنی.",
       "در سه جمله بگو عنصر معنایی برای موتور جستجو و برای هم‌تیمی که کد را می‌خواند چه فایده‌ای دارد."],
      ["Lay out an article page with header, main, section, and aside. Beside it, write the same layout with only div elements, and say which you would ship.",
       "In three sentences, say how a semantic element helps a search engine and a teammate reading the code."],
      ("https://developer.mozilla.org/en-US/docs/Glossary/Semantics",
       "معنا در HTML", "Semantics in HTML")),

    S("p2-assess-html", "p2", "ساختار با HTML", "Structure with HTML",
      "02-poodman-2-static-web/01-html.md", 114, 115,
      "ارزشیابی HTML", "HTML assessment",
      ["صفحه ارزشیابی را بدون دیدن نمونه بساز: عنوان، متن، تصویر، فرم کوتاه، و حداقل دو عنصر معنایی.",
       "فایل نهایی را به هم‌گروهی بده تا فقط با خواندن کد بگوید هر بخش صفحه چه کاری می‌کند."],
      ["Build the assessment page without looking at a sample: a heading, text, an image, a short form, and at least two semantic elements.",
       "Give the finished file to a partner and ask them to say what each part of the page does, using only the code."],
      None),

    S("p2-css-start", "p2", "ظاهر با CSS", "Appearance with CSS",
      "02-poodman-2-static-web/02-css.md", 116, 120,
      "نوشتن CSS", "Writing CSS",
      ["یک قانون CSS را یک بار داخل صفحه و یک بار در فایل جدا بنویس. بگو برای پروژه کلاسی کدام را نگه می‌داری.",
       "بالای یک قانون یک توضیح CSS بنویس که بگوید این رنگ برای چه بخشی است. توضیح نباید در صفحه دیده شود."],
      ["Write one CSS rule once inside the page and once in a separate file. Say which you would keep for a class project.",
       "Put a CSS comment above a rule explaining which part the color is for. The comment must not show on the page."],
      (MDN_CSS + "/First_steps", "اولین قدم‌های CSS", "CSS first steps")),

    S("p2-css-look", "p2", "ظاهر با CSS", "Appearance with CSS",
      "02-poodman-2-static-web/02-css.md", 121, 127,
      "رنگ، پس‌زمینه و انتخاب‌گر", "Color, background, and selectors",
      ["با انتخاب‌گر عنصر، کلاس، شناسه و گروه، چهار قانون متفاوت روی یک صفحه اعمال کن. بعد یک انتخاب‌گر ویژگی برای inputهای لازم بنویس.",
       "یک تصویر پس‌زمینه بساز و attachment را طوری تنظیم کن که هنگام اسکرول رفتارش را ببینی. نتیجه را در یک جمله بنویس."],
      ["Apply four different rules with an element selector, a class, an id, and a group selector. Then write an attribute selector for the required inputs.",
       "Set a background image and adjust attachment so you can see what happens when you scroll. Describe the result in one sentence."],
      (MDN_CSS + "/Building_blocks/Selectors", "انتخاب‌گرها", "Selectors")),

    S("p2-box", "p2", "ظاهر با CSS", "Appearance with CSS",
      "02-poodman-2-static-web/02-css.md", 128, 131,
      "مدل جعبه‌ای و display", "The box model and display",
      ["برای یک جعبه، margin و padding و border را با عددهای متفاوت بگذار و در مرورگر اندازه کل را با اندازه محتوا مقایسه کن.",
       "سه عنصر را یک بار block، یک بار inline و یک بار inline-block کن. کدام را برای دکمه‌های یک فرم ورود انتخاب می‌کنی؟"],
      ["Give a box different margin, padding, and border values, and compare the total size with the content size in the browser.",
       "Set three elements to block, inline, and inline-block. Which would you choose for the buttons of a login form?"],
      (MDN_CSS + "/Building_blocks/The_box_model", "مدل جعبه‌ای", "The box model")),

    S("p2-flex", "p2", "ظاهر با CSS", "Appearance with CSS",
      "02-poodman-2-static-web/02-css.md", 132, 138,
      "چیدمان با Flexbox", "Layout with Flexbox",
      ["یک نوار منو با Flexbox بساز که آیتم‌ها در یک ردیف باشند و در عرض کم به خط بعد بروند. align-items را هم عوض کن و فرق را بنویس.",
       "سه کارت هم‌ارتفاع کنار هم بچین. اگر یکی متن طولانی‌تری داشت، ارتفاع ردیف چه می‌شود؟"],
      ["Build a menu bar with Flexbox so the items sit in one row and wrap when the width is small. Also change align-items and note the difference.",
       "Place three cards of equal height in a row. What happens to the row height if one card has a longer text?"],
      (MDN_CSS + "/CSS_layout/Flexbox", "فلکس‌باکس", "Flexbox")),

    S("p2-flex-work", "p2", "ظاهر با CSS", "Appearance with CSS",
      "02-poodman-2-static-web/02-css.md", 139, 141,
      "کارگاه چیدمان صفحه", "Page-layout workshop",
      ["بخش خدمات ویژه کتاب را با کارت‌هایی بساز که هر کدام تصویر و عنوان دارند. فاصله بین کارت‌ها را فقط با CSS تنظیم کن.",
       "رنگ پس‌زمینه موقت منو را بردار و بگو بدون آن، هنوز از کجا می‌فهمی ناحیه‌ها جدا هستند."],
      ["Build the book's featured-services block with cards that each have an image and a title. Set the gap between cards with CSS only.",
       "Remove the temporary menu background color, and say how you can still tell the regions apart."],
      None),

    S("p2-media", "p2", "ظاهر با CSS", "Appearance with CSS",
      "02-poodman-2-static-web/02-css.md", 142, 144,
      "مدیا کوئری و ارزشیابی CSS", "Media queries and the CSS assessment",
      ["یک مدیا کوئری بنویس که زیر ۶۰۰ پیکسل، منو را عمودی کند. عرض مرورگر را کم کن و قبل و بعد را مقایسه کن.",
       "صفحه ارزشیابی را با div و span فقط جایی که معنا ندارند کامل کن، و یک توضیح کوتاه بالای قانون‌های مهم بگذار."],
      ["Write a media query that stacks the menu vertically below 600 pixels. Narrow the browser and compare before and after.",
       "Finish the assessment page, using div and span only where there is no better meaning, and add a short comment above the important rules."],
      (MDN_CSS + "/CSS_layout/Media_queries", "مدیا کوئری", "Media queries")),

    S("p3-intro", "p3", "معرفی پودمان", "Module introduction",
      "03-poodman-3-interactive-web/00-intro.md", 145, 145,
      "معرفی پودمان تعاملی", "Introducing the interactive module",
      ["دو کار را نام ببر که بوت‌استرپ انجام می‌دهد و دو کار را که بدون جاوااسکریپت ممکن نیست.",
       "یک جزء از یک فروشگاه اینترنتی را انتخاب کن و بگو در این پودمان با کدام ابزار ساخته می‌شود."],
      ["Name two jobs Bootstrap does, and two jobs that are impossible without JavaScript.",
       "Pick one piece of an online shop and say which tool in this module builds it."],
      (BS, "شروع بوت‌استرپ", "Get started with Bootstrap")),

    S("p3-bs-start", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 146, 150,
      "فریم‌ورک و شروع بوت‌استرپ", "Frameworks and starting Bootstrap",
      ["بوت‌استرپ را به یک صفحه خالی وصل کن و فقط با کلاس‌های آماده یک دکمه و یک هشدار رنگی نشان بده.",
       "در دو جمله بنویس فریم‌ورک چه چیزی را حاضر می‌کند که خودت در پودمان قبل با CSS نوشتی."],
      ["Connect Bootstrap to an empty page and, using only ready-made classes, show a button and a colored alert.",
       "In two sentences, say what a framework already provides that you wrote yourself with CSS in the previous module."],
      (BS, "معرفی بوت‌استرپ ۵", "Bootstrap 5 introduction")),

    S("p3-bs-util", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 151, 155,
      "فاصله، گردی و لیست", "Spacing, rounding, and lists",
      ["چهار مقدار margin و padding را با کلاس‌های بوت‌استرپ روی یک کارت امتحان کن و بگو هر کلاس کدام ضلع را عوض می‌کند.",
       "یک لیست را با list-unstyled ساده کن و یک تصویر کوچک را با rounded-circle گرد کن."],
      ["Try four margin and padding utilities on one card, and say which side each class changes.",
       "Simplify a list with list-unstyled, and make a small image a circle with rounded-circle."],
      ("https://getbootstrap.com/docs/5.3/utilities/spacing/", "کلاس‌های فاصله", "Spacing utilities")),

    S("p3-bs-header", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 156, 159,
      "سرصفحه فروشگاه", "The shop header",
      ["سرصفحه‌ای با لوگو، جستجو و ورود بساز. در نمای باریک، لوگو و ورود را پنهان کن و بگو کاربر هنوز چطور جستجو می‌کند.",
       "آیتم‌های منو را در محور افقی وسط‌چین کن. نام کلاسی که این کار را کرد در دفترت بنویس."],
      ["Build a header with a logo, a search box, and a sign-in link. On a narrow view, hide the logo and sign-in, and say how the user can still search.",
       "Center the menu items on the horizontal axis. Write down the class that did it."],
      ("https://getbootstrap.com/docs/5.3/utilities/display/", "نمایش و پنهان کردن", "Display utilities")),

    S("p3-bs-grid", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 160, 165,
      "شبکه Grid", "The grid",
      ["یک ردیف سه ستونه بساز که در موبایل زیر هم و در نمایش بزرگ کنار هم باشند. اگر به جای کلاس واکنش‌گرا فقط col بگذاری چه می‌شود؟",
       "یک آیکن شبکه اجتماعی را پیدا کن و کنار متن یک پاراگراف وسط‌چین بگذار."],
      ["Build a row of three columns that stack on a phone and sit side by side on a large screen. What happens if you use only col instead of a responsive class?",
       "Find a social-network icon and place it beside a centered paragraph."],
      ("https://getbootstrap.com/docs/5.3/layout/grid/", "سیستم شبکه", "Grid system")),

    S("p3-bs-rwd", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 166, 172,
      "کلاس‌های واکنش‌گرا", "Responsive classes",
      ["بلوک تازه‌ترین محصول‌ها را اضافه کن و عرض container را در دو اندازه صفحه مقایسه کن.",
       "یک نوار پایین برای موبایل با d-flex و d-lg-none بساز و یک تصویر را با img-fluid واکنش‌گرا کن. بگو چرا img-fluid به‌تنهایی کافی نیست."],
      ["Add the newest-products block and compare the container width at two screen sizes.",
       "Build a mobile bottom bar with d-flex and d-lg-none, and make an image responsive with img-fluid. Say why img-fluid alone is not the whole job."],
      ("https://getbootstrap.com/docs/5.3/layout/containers/", "کانتینرها", "Containers")),

    S("p3-bs-nav", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 173, 179,
      "نوار ناوبری و جزئیات محصول", "Navbar and product details",
      ["یک navbar با زیرمنو (dropdown) بساز و در عرض کم جمع شدنش را امتحان کن.",
       "صفحه جزئیات محصول را در سه ستون بچین: تصویر، توضیح، و قیمت. محتوای ستون‌ها را از هم جدا نگه دار."],
      ["Build a navbar with a dropdown, and test how it collapses when the width is small.",
       "Lay out a product-details page in three columns: image, description, and price. Keep the column contents distinct."],
      ("https://getbootstrap.com/docs/5.3/components/navbar/", "نوار ناوبری", "Navbar")),

    S("p3-bs-form", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 180, 184,
      "فرم و پنجره Modal", "Forms and modals",
      ["فرم ثبت‌نام را افقی وسط صفحه بگذار و حداقل سه کنترل را با کلاس فرم بوت‌استرپ استایل بده.",
       "یک modal با عنوان، متن و دکمه بستن بساز. tabindex را در یک جمله توضیح بده."],
      ["Center the signup form horizontally and style at least three controls with Bootstrap form classes.",
       "Build a modal with a title, text, and a close button. Explain tabindex in one sentence."],
      ("https://getbootstrap.com/docs/5.3/components/modal/", "پنجره modal", "Modal")),

    S("p3-bs-show", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 185, 189,
      "کاروسل و آکاردئون", "Carousel and accordion",
      ["یک کاروسل با دو تصویر بساز و دکمه‌های بعدی و قبلی را امتحان کن.",
       "بخش پرسش‌های متداول را با آکاردئون سه سؤال بساز، طوری که با باز شدن یکی، بقیه جمع شوند."],
      ["Build a carousel with two images and try the next and previous controls.",
       "Build a three-question FAQ with an accordion so that opening one item collapses the others."],
      ("https://getbootstrap.com/docs/5.3/components/carousel/", "کاروسل", "Carousel")),

    S("p3-bs-assess", "p3", "بوت‌استرپ", "Bootstrap",
      "03-poodman-3-interactive-web/01-bootstrap.md", 190, 191,
      "ارزشیابی بوت‌استرپ", "Bootstrap assessment",
      ["چهار کار ارزشیابی را در یک صفحه جمع کن: navbar واکنش‌گرا، فرم معتبر، modal، و carousel. هر کدام باید واقعاً کار کند.",
       "عرض صفحه را از موبایل تا دسکتاپ تغییر بده و یک ایراد چیدمان را که دیدی بنویس و درست کن."],
      ["Put the four assessment pieces on one page: a responsive navbar, a valid form, a modal, and a carousel. Each one has to work.",
       "Resize from phone width to desktop, write down one layout problem you see, and fix it."],
      None),

    S("p3-js-start", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 192, 197,
      "جاوااسکریپت در صفحه وب", "JavaScript on the page",
      ["یک اسکریپت در انتهای body بنویس که یک جمله در کنسول چاپ کند، و همان جمله را یک بار با document.write در صفحه نشان بده. فرق محل نمایش را بنویس.",
       "همان اسکریپت را به head منتقل کن و بگو ترتیب اجرا نسبت به ساختن صفحه چه فرقی کرد."],
      ["Write a script at the end of body that prints one sentence in the console, and show the same sentence once with document.write. Note where each result appears.",
       "Move that script into the head and say how the order of running changed relative to building the page."],
      (MDN_JS + "/First_steps/What_is_JavaScript", "جاوااسکریپت چیست", "What is JavaScript")),

    S("p3-js-vars", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 198, 202,
      "متغیر و نوع داده", "Variables and data types",
      ["چهار متغیر با نوع‌های مختلف بساز و typeof هر کدام را در کنسول چاپ کن.",
       "یک رشته عددی را صریحاً به عدد تبدیل کن و قبل و بعد، نوعش را نشان بده. تبدیل خودکار را با یک مثال جمع رشته و عدد هم نشان بده."],
      ["Create four variables of different types and print typeof for each in the console.",
       "Explicitly convert a numeric string to a number and show the type before and after. Also show automatic conversion by adding a string and a number."],
      (MDN_JS + "/First_steps/Variables", "متغیرها", "Variables")),

    S("p3-js-ops", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 203, 205,
      "عملگرها", "Operators",
      ["قیمت و تخفیف را با عملگرهای ریاضی حساب کن. بعد با عملگر مقایسه‌ای بگو آیا قیمت نهایی از ۱۰۰ کمتر است.",
       "فرق == و === را با یک عدد و یک رشته عددی نشان بده و بنویس کدام را در فرم فروشگاه استفاده می‌کنی."],
      ["Compute a price and a discount with arithmetic operators. Then use a comparison to say whether the final price is under 100.",
       "Show the difference between == and === with a number and a numeric string, and say which you would use in a shop form."],
      ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_operators",
       "عبارت‌ها و عملگرها", "Expressions and operators")),

    S("p3-js-data", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 206, 210,
      "آرایه و شیء", "Arrays and objects",
      ["آرایه‌ای از سه محصول بساز، یکی اضافه کن، و همه را چاپ کن. سپس یک شیء محصول با نام، قیمت و موجودی بساز و فقط قیمت را عوض کن.",
       "بگو چه چیزی را در آرایه می‌گذاری و چه چیزی را در شیء. یک مثال از هر کدام در فروشگاه بیاور."],
      ["Build an array of three products, add one, and print them all. Then make a product object with name, price, and stock, and change only the price.",
       "Say what you store in an array and what you store in an object. Give one shop example of each."],
      (MDN_JS + "/First_steps/Arrays", "آرایه‌ها", "Arrays")),

    S("p3-js-if", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 211, 212,
      "شرط در جاوااسکریپت", "Conditions in JavaScript",
      ["اگر موجودی صفر بود «ناموجود» چاپ کن، اگر کمتر از ۵ بود «رو به اتمام»، وگرنه «موجود».",
       "دو شرط را با && ترکیب کن: کاربر وارد شده باشد و سبد خرید خالی نباشد. یک حالت که هیچ کدام درست نیست را هم اجرا کن."],
      ["If stock is 0 print «out of stock», if it is under 5 print «low», otherwise print «in stock».",
       "Combine two conditions with &&: the user is signed in and the cart is not empty. Also run a case where neither condition is true."],
      ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling",
       "کنترل جریان", "Control flow")),

    S("p3-js-loops", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 213, 218,
      "حلقه‌ها", "Loops",
      ["با for قیمت‌های یک آرایه را جمع کن. با for...of همان کار را کوتاه‌تر بنویس. یک continue بگذار که قیمت صفر را نادیده بگیرد.",
       "کلیدهای یک شیء زبان‌ها را با حلقه مناسب چاپ کن و بگو چرا برای شیء از همان حلقه آرایه استفاده نکردی."],
      ["Sum the prices in an array with for. Write the same task more briefly with for...of. Use continue to skip a price of 0.",
       "Print the keys of a languages object with a suitable loop, and say why you did not use the same loop you used for the array."],
      ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration",
       "حلقه و تکرار", "Loops and iteration")),

    S("p3-js-func", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 219, 224,
      "تابع‌ها", "Functions",
      ["تابعی بنویس که قیمت و درصد تخفیف را بگیرد و قیمت نهایی را برگرداند. آن را برای دو کالا صدا بزن.",
       "یک کار رشته‌ای (مثلاً بزرگ‌کردن حرف اول نام کالا) و یک کار Math (مثلاً گرد کردن قیمت) را با تابع آماده انجام بده و کنارش بگو پارامتر و آرگومان کدام بود."],
      ["Write a function that takes a price and a discount percent and returns the final price. Call it for two products.",
       "Do one string job (for example, capitalize a product name) and one Math job (for example, round a price) with a built-in function, and say which part was the parameter and which was the argument."],
      ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions",
       "تابع‌ها", "Functions")),

    S("p3-js-dom", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 225, 230,
      "صفحه، رویداد و اعتبار فرم", "The page, events, and form validation",
      ["با کلیک روی یک دکمه، متن یک پاراگراف را عوض کن. کد را بعد از وجود داشتن عنصر در صفحه اجرا کن.",
       "تابع validateForm را برای یک فرم دو فیلدی بنویس که فیلد خالی را قبول نکند و پیام خطا را در خود صفحه نشان بدهد، نه فقط در alert."],
      ["On a button click, change a paragraph's text. Run the code only after the element exists on the page.",
       "Write validateForm for a two-field form that rejects an empty field and shows the error on the page itself, not only in an alert."],
      (MDN_JS + "/Client-side_web_APIs/Manipulating_documents",
       "تغییر سند", "Manipulating documents")),

    S("p3-js-assess", "p3", "جاوااسکریپت", "JavaScript",
      "03-poodman-3-interactive-web/02-javascript.md", 231, 232,
      "ارزشیابی جاوااسکریپت", "JavaScript assessment",
      ["یک صفحه کوچک بساز که تابع، آرایه محصولات، و یک دکمه برای فیلتر کردن قیمت‌های بالای مقدار واردشده داشته باشد.",
       "فرق پارامتر و آرگومان را با همان تابع فیلتر، در دو سطر و با عددهای واقعی توضیح بده."],
      ["Build a small page with a function, a products array, and a button that filters prices above the value the user typed.",
       "Using that filter function, explain parameter versus argument in two lines with real numbers."],
      None),

    S("p4-intro", "p4", "معرفی پودمان", "Module introduction",
      "04-poodman-4-python-oop/00-intro.md", 233, 233,
      "معرفی پودمان شیءگرایی", "Introducing the object-oriented module",
      ["یک شیء از زندگی روزمره (غیر از گوشی) انتخاب کن و برایش سه ویژگی و دو رفتار بنویس.",
       "بگو چرا وقتی برنامه بزرگ می‌شود، نگه داشتن همه‌چیز در چند لیست سخت می‌شود."],
      ["Pick an everyday object other than a phone, and write three attributes and two behaviors for it.",
       "Say why keeping everything in a few lists gets hard once a program grows."],
      (PY + "classes.html", "کلاس‌ها در پایتون", "Classes in Python")),

    S("p4-idea", "p4", "شیءگرایی", "Object-oriented programming",
      "04-poodman-4-python-oop/01-object-oriented.md", 234, 237,
      "ایده شیء و کلاس", "The idea of objects and classes",
      ["برای «کتاب کتابخانه» کلاس را از شیء جدا کن: کلاس چه چیزی است و دو شیء مختلف چه فرقی دارند؟",
       "ویژگی و متد را با مثال گوشی کتاب در دو ستون بنویس."],
      ["For a «library book», separate the class from the object: what is the class, and how do two different objects differ?",
       "Write attributes and methods in two columns, using the book's phone example."],
      (PY + "classes.html", "کلاس‌ها", "Classes")),

    S("p4-class", "p4", "شیءگرایی", "Object-oriented programming",
      "04-poodman-4-python-oop/01-object-oriented.md", 238, 243,
      "ساخت کلاس و متد", "Writing a class and methods",
      ["کلاس Mobile را با برند، مدل و رنگ بساز، دو شیء از آن بگیر و متد show_info را برای هر دو صدا بزن.",
       "یک ویژگی را بعد از ساخت شیء عوض کن. در کنار کد بنویس کدام خط سازنده است و کدام خط متد."],
      ["Write a Mobile class with brand, model, and color, create two objects, and call show_info on both.",
       "Change one attribute after creating the object. Beside the code, mark which line is the constructor and which line is the method."],
      (PY + "classes.html#class-objects", "شیءهای کلاس", "Class objects")),

    S("p4-inherit", "p4", "شیءگرایی", "Object-oriented programming",
      "04-poodman-4-python-oop/01-object-oriented.md", 244, 249,
      "وراثت", "Inheritance",
      ["کلاس فرزند Smartphone را از Mobile بساز که یک ویژگی دوربین اضافه دارد. متد والد را صدا بزن و یک متد تازه take_picture اضافه کن.",
       "همان متد show_info را در فرزند بازنویسی کن طوری که نام متد عوض نشود ولی جمله بیشتری چاپ کند. بگو چرا این کار مفید است."],
      ["Create a Smartphone child of Mobile that adds a camera attribute. Call a parent method and add a new take_picture method.",
       "Override show_info in the child so the method name stays the same but it prints an extra sentence. Say why that is useful."],
      (PY + "classes.html#inheritance", "وراثت", "Inheritance")),

    S("p4-protect", "p4", "شیءگرایی", "Object-oriented programming",
      "04-poodman-4-python-oop/01-object-oriented.md", 250, 251,
      "داده معتبر و استفاده داخلی", "Valid data and internal use",
      ["سازنده را طوری بنویس که رنگ خالی یا قیمت منفی را قبول نکند و پیام روشن بدهد.",
       "یک ویژگی را با قرارداد استفاده داخلی نام‌گذاری کن و در دو سطر بگو این نام برای چه کسی نوشته شده: استفاده کلاس، نه استفاده آزاد بیرون."],
      ["Write the constructor so it rejects an empty color or a negative price and gives a clear message.",
       "Name one attribute with the internal-use convention, and in two lines say who that name is for: the class, not free use from outside."],
      (PY + "classes.html#private-variables", "متغیرهای داخلی", "Private variables")),

    S("p4-assess-oop", "p4", "شیءگرایی", "Object-oriented programming",
      "04-poodman-4-python-oop/01-object-oriented.md", 252, 253,
      "ارزشیابی برنامه شیءگرا", "Object-oriented assessment",
      ["یک کلاس پایه و یک کلاس فرزند برای وسایل آزمایشگاه کامپیوتر بنویس و دو شیء بساز. خروجی باید ویژگی‌ها و یک رفتار را نشان بدهد.",
       "یک مقدار نامعتبر را عمداً بده و نشان بده برنامه‌ات به‌جای ادامه خاموش، پیام می‌دهد."],
      ["Write a base class and a child class for computer-lab equipment, and create two objects. The output should show the attributes and one behavior.",
       "Pass an invalid value on purpose and show that your program reports it instead of continuing silently."],
      None),

    S("p4-files", "p4", "فایل و توسعه", "Files and development",
      "04-poodman-4-python-oop/02-object-oriented-development.md", 254, 259,
      "خواندن و نوشتن فایل متنی", "Reading and writing text files",
      ["برندها را در یک فایل متنی بنویس و دوباره بخوان و چاپ کن. مسیر فایل را یک بار نسبی و یک بار با توضیح مسیر کامل مقایسه کن.",
       "اگر فایل هنوز ساخته نشده باشد، برنامه چه خطایی می‌دهد؟ خطا را یک بار ببین و بعد فایل را سر جایش بگذار."],
      ["Write the brands into a text file, then read them back and print them. Compare a relative path with a full path in a short note.",
       "What error do you get if the file does not exist yet? See the error once, then put the file in place."],
      (PY + "inputoutput.html#reading-and-writing-files", "خواندن و نوشتن فایل", "Reading and writing files")),

    S("p4-errors", "p4", "فایل و توسعه", "Files and development",
      "04-poodman-4-python-oop/02-object-oriented-development.md", 260, 266,
      "پیمایش فایل و مدیریت خطا", "Walking a file and handling errors",
      ["خط‌های فایل را با for بخوان و شماره خط را کنار هر برند چاپ کن. سپس یک برند تازه را بدون پاک کردن قبلی‌ها به فایل اضافه کن.",
       "تقسیم دو عدد را داخل try و except بگذار، از جمله تقسیم بر صفر. پیام خطا باید مال برنامه تو باشد، نه فقط متن پیش‌فرض پایتون."],
      ["Read the file lines with for and print a line number beside each brand. Then append a new brand without erasing the old ones.",
       "Put division of two numbers inside try and except, including division by zero. The message should be your program's, not only Python's default text."],
      ("https://docs.python.org/3/tutorial/errors.html", "خطاها و استثناها", "Errors and exceptions")),

    S("p4-json", "p4", "فایل و توسعه", "Files and development",
      "04-poodman-4-python-oop/02-object-oriented-development.md", 267, 272,
      "چند فایل و JSON", "Several files and JSON",
      ["اگر یکی از چند فایل پیدا نشد، یک بار به کاربر خبر بده و یک بار همان خطا را آرام نادیده بگیر. بگو کدام رفتار را برای برنامه کلاسی می‌خواهی و چرا.",
       "یک لیست دیکشنری از گوشی‌ها را با json.dump ذخیره کن و با json.loads برگردان. یک فیلد را در فایل عوض کن و دوباره بخوان."],
      ["If one of several files is missing, tell the user once, and once ignore that error quietly. Say which behavior you want for a class program and why.",
       "Save a list of phone dictionaries with json.dump and read it back with json.loads. Change one field in the file and read it again."],
      ("https://docs.python.org/3/library/json.html", "ماژول json", "The json module")),

    S("p4-assess-files", "p4", "فایل و توسعه", "Files and development",
      "04-poodman-4-python-oop/02-object-oriented-development.md", 273, 274,
      "ارزشیابی کار با فایل", "Files assessment",
      ["برنامه ارزشیابی را کامل کن: داده را به JSON تبدیل کن، در فایل بگذار، برنامه را ببند و دوباره باز کن و همان داده را برگردان.",
       "عمداً یک JSON خراب در فایل بگذار و با except جلوی بسته شدن بی‌خبر برنامه را بگیر."],
      ["Finish the assessment program: convert data to JSON, store it, quit, start again, and get the same data back.",
       "Put a broken JSON file in place on purpose, and use except so the program does not close without a message."],
      None),

    S("p5-intro", "p5", "معرفی پودمان", "Module introduction",
      "05-poodman-5-django/00-intro.md", 275, 275,
      "معرفی پودمان جنگو", "Introducing the Django module",
      ["سه بخش یک وب‌اپلیکیشن را نام ببر که در پودمان‌های قبل جدا بودند و جنگو کنار هم می‌آورد.",
       "پروژه آب‌وهوای کتاب را در یک جمله تعریف کن: کاربر چه می‌دهد و چه می‌بیند؟"],
      ["Name three parts of a web app that earlier modules treated separately and that Django brings together.",
       "Define the book's weather project in one sentence: what does the user give, and what do they see?"],
      (DJ, "آموزش رسمی جنگو", "Official Django tutorial")),

    S("p5-what", "p5", "ایجاد وب‌اپلیکیشن", "Creating the web app",
      "05-poodman-5-django/01-create-web-app.md", 276, 279,
      "جنگو چیست و نصب", "What Django is, and installing it",
      ["نسخه جنگو و نسخه پایتون رایانه خودت را با دستور مناسب چاپ کن و کنار نسخه کتاب بنویس.",
       "در چهار کلمه بگو پروژه جنگو چه فرقی با یک فایل HTML تنها دارد."],
      ["Print your Django version and your Python version, and write them next to the versions in the book.",
       "In a few words, say how a Django project differs from a single HTML file."],
      ("https://docs.djangoproject.com/en/stable/intro/install/", "نصب جنگو", "Installing Django")),

    S("p5-project", "p5", "ایجاد وب‌اپلیکیشن", "Creating the web app",
      "05-poodman-5-django/01-create-web-app.md", 280, 286,
      "پروژه، اپ و اولین view", "Project, app, and the first view",
      ["پروژه را بساز، migrate را اجرا کن و بگو فایل db.sqlite3 برای چیست. بعد اپ آب‌وهوا را با startapp اضافه کن.",
       "یک view که یک جمله ساده برمی‌گرداند به urls وصل کن و در مرورگر باز کن. اگر مسیر را در urls ننویسی چه می‌بینی؟"],
      ["Create the project, run migrate, and say what db.sqlite3 is for. Then add the weather app with startapp.",
       "Connect a view that returns one plain sentence to urls and open it in the browser. What do you see if you leave it out of urls?"],
      (DJ, "آموزش ۱: درخواست و پاسخ", "Tutorial 1: requests and responses")),

    S("p5-template", "p5", "ایجاد وب‌اپلیکیشن", "Creating the web app",
      "05-poodman-5-django/01-create-web-app.md", 287, 292,
      "قالب و دمای واقعی", "Templates and a real temperature",
      ["داده را از view با render به قالب بفرست و در HTML نشان بده. یک متغیر را عمداً در قالب جا بینداز تا جای خالی را ببینی.",
       "مختصات عرض و طول را برای یک شهر بفرست و نتیجه را نشان بده. اگر یکی از این دو مقدار نیاید، برنامه باید چه بگوید؟"],
      ["Send data from the view to the template with render and show it in HTML. Leave one variable out of the template on purpose so you can see the blank.",
       "Send latitude and longitude for one city and show the result. What should the program say if either value is missing?"],
      ("https://docs.djangoproject.com/en/stable/intro/tutorial03/",
       "آموزش ۳: نما و قالب", "Tutorial 3: views and templates")),

    S("p5-assess-create", "p5", "ایجاد وب‌اپلیکیشن", "Creating the web app",
      "05-poodman-5-django/01-create-web-app.md", 293, 294,
      "ارزشیابی ایجاد وب‌اپلیکیشن", "Creating-the-app assessment",
      ["از صفر تا یک صفحه که نام شهر را نشان می‌دهد را بدون نگاه به جزوه بنویس: پروژه، اپ، view، url، قالب.",
       "سرور را خاموش و روشن کن و بگو کدام فایل‌ها را اگر پاک کنی صفحه دیگر باز نمی‌شود."],
      ["Without notes, go from nothing to a page that shows a city name: project, app, view, url, template.",
       "Stop and start the server, and say which files you could delete and still not have a working page."],
      None),

    S("p5-model", "p5", "توسعه وب‌اپلیکیشن", "Developing the web app",
      "05-poodman-5-django/02-develop-web-app.md", 295, 304,
      "مدل شهر و پنل ادمین", "The city model and the admin",
      ["مدل City را بساز، migrate کن، و در ادمین یک شهر ثبت کن. نام جدول ساخته‌شده را با پیشوند اپ بنویس.",
       "فیلدها را طوری انتخاب کن که شهر بدون نام ذخیره نشود. یک شهر را از پنل ویرایش کن و نتیجه را در فهرست ببین."],
      ["Create the City model, migrate, and add one city in the admin. Write the table name, including the app prefix.",
       "Choose fields so a city cannot be saved without a name. Edit one city in the admin and see the result in the list."],
      ("https://docs.djangoproject.com/en/stable/intro/tutorial02/",
       "آموزش ۲: مدل و ادمین", "Tutorial 2: models and the admin")),

    S("p5-list", "p5", "توسعه وب‌اپلیکیشن", "Developing the web app",
      "05-poodman-5-django/02-develop-web-app.md", 305, 312,
      "خواندن شهرها و نمایش فهرست", "Reading cities and showing the list",
      ["همه شهرها را از پایگاه بخوان و در یک صفحه فهرست کن. اگر هیچ شهری نبود، یک جمله به‌جای جدول خالی نشان بده.",
       "لینک هر شهر را به صفحه جزئیات وصل کن و با یک شهر واقعی امتحان کن."],
      ["Read every city from the database and list them on one page. If there are no cities, show a sentence instead of an empty table.",
       "Link each city to a detail page and try it with a real city."],
      ("https://docs.djangoproject.com/en/stable/topics/db/queries/",
       "پرس‌وجوها", "Making queries")),

    S("p5-auth", "p5", "توسعه وب‌اپلیکیشن", "Developing the web app",
      "05-poodman-5-django/02-develop-web-app.md", 313, 319,
      "ورود و خروج", "Sign-in and sign-out",
      ["بعد از ورود، کاربر به صفحه اصلی برگردد و دکمه خروج را ببیند. یک بار بدون ورود همان صفحه را باز کن و فرق را بنویس.",
       "آدرس بعد از login و logout را در تنظیمات پیدا کن و بگو اگر اشتباه باشد کاربر کجا می‌ماند."],
      ["After sign-in, send the user back to the home page and show a sign-out button. Open the same page once while signed out and note the difference.",
       "Find the post-login and post-logout addresses in settings, and say where the user gets stuck if they are wrong."],
      ("https://docs.djangoproject.com/en/stable/topics/auth/default/",
       "احراز هویت جنگو", "Django authentication")),

    S("p5-crud", "p5", "توسعه وب‌اپلیکیشن", "Developing the web app",
      "05-poodman-5-django/02-develop-web-app.md", 320, 325,
      "افزودن و حذف شهر", "Adding and deleting a city",
      ["فرم افزودن شهر را از view به قالب بفرست و یک شهر جدید را از خود سایت، نه از ادمین، ثبت کن.",
       "لینک حذف را کنار هر شهر بگذار و بعد از حذف، فهرست را تازه کن. حذف یک شهر را دو بار امتحان کن و بگو بار دوم چه می‌شود."],
      ["Send the add-city form from the view to the template, and save a new city from the site itself, not from the admin.",
       "Put a delete link beside each city and refresh the list after deletion. Try deleting one city twice and say what happens the second time."],
      ("https://docs.djangoproject.com/en/stable/topics/forms/",
       "فرم‌ها در جنگو", "Working with forms")),

    S("p5-bugs", "p5", "توسعه وب‌اپلیکیشن", "Developing the web app",
      "05-poodman-5-django/02-develop-web-app.md", 326, 329,
      "باگ و امنیت", "Bugs and security",
      ["یک باگ منطقی و یک خطای اجرایی از برنامه آب‌وهوا پیدا کن یا عمداً بساز. برای هر کدام بنویس نشانه ظاهری‌اش چیست و کجای کد را درست کردی.",
       "یک ورودی فرم را با علامت‌های خاص پر کن و بگو اگر داده را بدون مراقبت در صفحه بگذاری چه خطری برای کاربر بعدی دارد."],
      ["Find or deliberately create one logic bug and one runtime error in the weather app. For each, write the visible symptom and which part of the code you fixed.",
       "Fill a form field with unusual characters, and say what risk the next user faces if that data is placed on the page without care."],
      ("https://docs.djangoproject.com/en/stable/topics/security/",
       "امنیت در جنگو", "Security in Django")),

    S("refs", "back", "منابع", "References", "06-references.md", 330, 330,
      "منابع کتاب", "Book references",
      ["سه منبع این فصل را انتخاب کن و برای هر کدام بنویس به کدام پودمان درس مربوط است.",
       "یکی از پیوندها را باز کن و یک نکته‌ای را که در کتاب نبود در دو سطر بنویس. اگر اینترنت نداری، فقط نشانی را در دفترت نگه دار."],
      ["Pick three sources from this chapter and write which module each one supports.",
       "Open one link and write two lines about something the book did not say. If you are offline, keep the address in your notes instead."],
      None),
]

from practical import PRACTICAL

for _section in SECTIONS:
    _pair = PRACTICAL.get(_section["id"])
    if _pair:
        _section["ex_fa"], _section["ex_en"] = _pair
