"""Build-it exercises. These are not in the printed book."""

PRACTICAL = {
    "toc": (
        ["یک صفحه HTML بساز که پنج پودمان را به صورت فهرست نشان بدهد و هر مورد به یک تیتر در همان صفحه پیوند داشته باشد.",
         "در پایتون برنامه‌ای بنویس که نام پنج پودمان را چاپ کند و از کاربر بپرسد شماره پودمان این هفته چند است، بعد فقط همان نام را دوباره چاپ کند."],
        ["Build an HTML page that lists the five modules, each linking to a heading on the same page.",
         "Write a Python program that prints the five module names, asks which number you will study this week, and prints only that name again."],
    ),
    "p1-intro": (
        ["برنامه‌ای بساز که نام، پایه و یک جمله خوشامد را در سه خط چاپ کند و آن را در فایل welcome.py ذخیره و اجرا کن.",
         "خروجی همان برنامه را طوری عوض کن که اگر نام خالی وارد شد، به جای آن «هنرجو» چاپ شود."],
        ["Build a program that prints your name, grade, and a welcome line. Save it as welcome.py and run it.",
         "Change that program so an empty name prints «student» instead."],
    ),
    "p1-python": (
        ["در IDLE فایل hello.py را بساز که یک پیام چندخطی با سه کوتیشن چاپ کند، آن را در پوشه PyProg ذخیره کن و با F5 اجرا کن.",
         "همان پوشه را با یک فایل دوم به نام notes.py کامل کن که سه قانون نام‌گذاری فایل را به صورت نظر در کد و یک print جدا نشان بدهد."],
        ["In IDLE, create hello.py that prints a multi-line message with triple quotes. Save it in a PyProg folder and run it with F5.",
         "Add notes.py in the same folder. Put three file-naming rules in comments and print one reminder."],
    ),
    "p1-vars": (
        ["برنامه‌ای بساز با سه متغیر نام کالا، قیمت صحیح و تخفیف اعشاری، بعد مبلغ بعد از تخفیف را حساب و همراه نوع هر متغیر چاپ کن.",
         "همان برنامه را گسترش بده تا دو رشته را با + بچسباند و دو عدد را با + جمع کند و هر دو نتیجه را پشت سر هم نشان بدهد."],
        ["Build a program with a product name, an integer price, and a float discount. Print the price after discount and the type of each variable.",
         "Extend it so + joins two strings and + adds two numbers, and show both results."],
    ),
    "p1-cast": (
        ["برنامه‌ای بساز که قیمت و تعداد را با input بگیرد، هر دو را به عدد تبدیل کند و مبلغ کل را چاپ کند.",
         "به همان برنامه یک ورودی سن اضافه کن و فقط اگر سن به ۱۵ رسیده باشد پیام «مجاز» را نشان بده."],
        ["Build a program that reads a price and a quantity with input, converts both to numbers, and prints the total.",
         "Add an age input to the same program and print «allowed» only when the age is at least 15."],
    ),
    "p1-lists": (
        ["یک لیست پنج خوراکی بساز. با برنامه یک مورد را در جایگاه دوم درج کن، یکی را با مقدار حذف کن، آخری را pop کن و بعد از هر تغییر لیست را چاپ کن.",
         "تابع کوچکی بنویس که جای عنصر اول و سوم همان لیست را عوض کند و لیست تازه را برگرداند."],
        ["Build a list of five snacks. Insert one at index 1, remove one by value, pop the last item, and print the list after each change.",
         "Write a small function that swaps the first and third items of that list and returns the new list."],
    ),
    "p1-if": (
        ["برنامه‌ای بساز که نمره را بگیرد و برای ۱۸ به بالا، زیر ۱۰، و بین آن‌ها سه پیام متفاوت چاپ کند.",
         "به آن یک رمز اضافه کن که فقط وقتی قبول شود که حداقل ۸ حرف داشته باشد و حداقل یک رقم داخلش باشد."],
        ["Build a program that reads a score and prints a different message for 18 or above, below 10, and the scores in between.",
         "Add a password check that accepts the password only when it has at least 8 characters and at least one digit."],
    ),
    "p1-elif": (
        ["یک منوی غذا با سه گزینه و یک شاخه خطا بساز، طوری که با یک بار اجرا فقط یک پیام مربوط به همان گزینه دیده شود.",
         "برنامه سطح بازی بساز که ورودی آسان، متوسط یا سخت را بگیرد و برای هر کدام یک جمله و یک امتیاز شروع متفاوت چاپ کند."],
        ["Build a three-item food menu with an error branch, so one run prints only the message for the chosen item.",
         "Build a game-level program that reads easy, medium, or hard and prints a different sentence and starting score for each."],
    ),
    "p1-for": (
        ["لیست چهار کالا را با for چاپ کن و وقتی به یک نام خاص رسیدی یک خط اضافه نشان بده و با continue به کالای بعدی برو.",
         "با range جمع ۱ تا ۲۰ را حساب کن و همان جمع را یک بار دیگر با گام ۲ دوباره بساز و هر دو عدد را چاپ کن."],
        ["Print four products with for. When you reach one chosen name, print an extra line and continue to the next product.",
         "Use range to add 1 through 20, then build the same kind of sum with a step of 2, and print both numbers."],
    ),
    "p1-while": (
        ["با while عدد بگیر و مربعش را چاپ کن تا کاربر ۰ وارد کند. ورودی غیرعددی نباید برنامه را ببندد.",
         "برنامه مهمان‌ها را بساز که نام‌ها را در یک لیست جمع کند تا کاربر «پایان» را بنویسد، بعد همه نام‌ها را چاپ کند."],
        ["With while, read numbers and print their squares until the user enters 0. A non-number must not close the program.",
         "Build a guest-list program that collects names until the user types «end», then prints every name."],
    ),
    "p1-assess-data": (
        ["یک برنامه فروشگاه کوچک بساز: لیست کالا، افزودن، حذف، و یک شرط که بگوید جمع قیمت‌ها از بودجه کاربر بیشتر است یا نه.",
         "همان برنامه را با یک حلقه کامل کن که بعد از هر عمل، کل لیست و جمع قیمت را دوباره نشان بدهد."],
        ["Build a tiny shop program: a product list, add, remove, and a condition that says whether the total is over the user's budget.",
         "Finish the same program with a loop that shows the whole list and the total after every action."],
    ),
    "p1-sets": (
        ["برنامه دو دانش‌آموز بساز که درس‌های مشترک و درس‌های مخصوص نفر اول را از روی دو مجموعه چاپ کند.",
         "همان برنامه را طوری کامل کن که افزودن درس تکراری تعداد مجموعه را عوض نکند و قبل و بعدِ طول را نشان بدهد."],
        ["Build a two-student program that prints the shared subjects and the subjects only the first student has.",
         "Finish it so adding a duplicate subject does not change the set size, and print the length before and after."],
    ),
    "p1-dict": (
        ["دفترچه تلفن بساز که سه نفر را نگه دارد، یک شماره را عوض کند، یک نفر را حذف کند و وجود یک نام را بررسی کند.",
         "نسخه تعاملی همان دفترچه را بساز که از کاربر سه نام و شماره جدید بگیرد و اگر نام تکراری بود شماره قبلی را عوض کند."],
        ["Build a phone book of three people. Change one number, delete one person, and test whether a name exists.",
         "Build an interactive version that reads three new names and numbers, and replaces the old number when the name already exists."],
    ),
    "p1-quiz": (
        ["بازی آزمون را با سه سؤال از درس خودتان بساز، امتیاز را نگه دار و در پایان چاپ کن.",
         "به بازی یک گزینه خروج اضافه کن که حلقه را واقعاً تمام کند و امتیاز تا همان لحظه را نشان بدهد."],
        ["Build the quiz with three questions from your own course. Keep the score and print it at the end.",
         "Add a quit choice that actually ends the loop and shows the score so far."],
    ),
    "p1-tuple": (
        ["برنامه‌ای بساز که نام مدیران را در یک تاپل نگه دارد و تلاش برای تغییر عضو دوم را داخل پیام خطای خودت نشان بدهد.",
         "کنار آن یک لیست از همان نام‌ها بساز و فقط لیست را قابل ویرایش کن تا فرق در خروجی برنامه دیده شود."],
        ["Build a program that stores administrator names in a tuple and shows your own message when code tries to change the second item.",
         "Beside it, store the same names in a list and make only the list editable, so the difference shows in the output."],
    ),
    "p1-func": (
        ["دو تابع بساز: یکی نام فروشگاه را چاپ کند و یکی دو قیمت بگیرد و قیمت بیشتر را برگرداند. نتیجه را در متغیر ذخیره کن.",
         "تابع خوشامد با دو مقدار پیش‌فرض بساز و آن را هم بدون آرگومان و هم با آرگومان صدا بزن."],
        ["Build two functions: one prints the shop name, one takes two prices and returns the higher one. Store the returned value.",
         "Build a greeting function with two default values and call it once with no arguments and once with arguments."],
    ),
    "p1-func-more": (
        ["تابعی بساز که لیست نام‌ها را بگیرد و تعداد نام‌های بلندتر از ۴ حرف را برگرداند. آن را روی یک لیست واقعی چاپ کن.",
         "برنامه‌ای بساز که یک رشته به‌هم‌ریخته را مرتب کند و فهرست مرتب‌شده را در یک خط نشان بدهد."],
        ["Build a function that takes a list of names and returns how many are longer than 4 letters. Print the result for a real list.",
         "Build a program that sorts a scrambled string and prints the sorted list on one line."],
    ),
    "p1-modules": (
        ["برنامه‌ای بساز که با random هر بار یک پیام از یک لیست را چاپ کند و با math جذر یک عدد ورودی را هم نشان بدهد.",
         "یک تابع خودت برای بریدن رشته از روی فاصله بنویس و خروجی‌اش را کنار خروجی split روی همان رشته چاپ کن."],
        ["Build a program that prints one random message from a list on each run, and also prints the square root of a number the user types.",
         "Write your own function that splits a string on spaces, and print its result next to split for the same string."],
    ),
    "p1-assess-func": (
        ["فایل shop.py بساز که تابع تخفیف داشته باشد. از یک برنامه اصلی آن را import کن و قیمت دو کالا را با آن حساب کن.",
         "به shop.py تابع خوشامد اضافه کن و هر دو تابع را از برنامه اصلی، هر کدام با دو داده متفاوت، صدا بزن."],
        ["Create shop.py with a discount function. Import it from a main program and calculate two product prices with it.",
         "Add a greeting function to shop.py and call both functions from the main program, each with two different inputs."],
    ),
    "p2-intro": (
        ["یک پوشه سایت بساز با index.html که فقط یک عنوان و یک پاراگراف دارد، و یک فایل style.css که رنگ همان عنوان را عوض می‌کند.",
         "به همان صفحه یک دکمه اضافه کن که هنوز کاری نمی‌کند، تا فرق صفحه ایستا با دکمه تعاملی در خود پروژه دیده شود."],
        ["Create a site folder with index.html that has only a heading and a paragraph, and a style.css that changes the heading color.",
         "Add a button to that page that does not do anything yet, so the static page and the future interactive control sit in one project."],
    ),
    "p2-web": (
        ["صفحه about.html بساز که مسیر درخواست را در چهار بند نشان بدهد: مرورگر، آدرس، سرور، پاسخ. هر بند یک تیتر باشد.",
         "همان پوشه را با یک نسخه دوم از همان فایل کامل کن که فقط روی رایانه باز شود، و در صفحه بنویس این نسخه میزبان ندارد."],
        ["Build about.html that shows the request path as four headings: browser, address, server, response.",
         "Add a second copy of the page in the same folder for opening on the computer, and write on the page that this copy has no host."],
    ),
    "p2-concepts": (
        ["برای کتابخانه مدرسه سه فایل HTML بساز: خانه، فهرست کتاب، تماس. در خانه، نقشه سایت را با پیوند به دو صفحه دیگر بگذار.",
         "با یک فایل CSS عرض صفحه را در دو حالت نشان بده: ستون‌ها کنار هم، و زیر ۶۰۰ پیکسل زیر هم."],
        ["Build three HTML files for a school library: home, book list, contact. On the home page, put a site map linking to the other two.",
         "With one CSS file, show the columns side by side, and stack them below 600 pixels."],
    ),
    "p2-tags": (
        ["صفحه اول سایت را با doctype، title زبانه، و یک h1 متفاوت از title بساز و در مرورگر باز کن.",
         "همان صفحه را در فایل index.html ذخیره کن و یک پاراگراف دوم به آن اضافه کن بدون اینکه ساختار اصلی را از نو بنویسی."],
        ["Build the first page with a doctype, a tab title, and an h1 that is not the same text as the title. Open it in the browser.",
         "Save that page as index.html and add a second paragraph without rewriting the whole structure."],
    ),
    "p2-text": (
        ["صفحه‌ای بساز با یک عنوان، یک متن تأکیدشده، فهرست کتاب‌های رشته، و پیوندی که به پایین همان صفحه برود.",
         "یک پیوند بیرونی به صفحه اضافه کن که در زبانه تازه باز شود و متن پیوند بگوید مقصد بیرون از این صفحه است."],
        ["Build a page with a heading, emphasized text, a list of books in your field, and a link that jumps to the bottom of the same page.",
         "Add an external link that opens in a new tab, and make the link text say the destination is outside this page."],
    ),
    "p2-img": (
        ["یک تصویر را با عرض و ارتفاع مشخص و alt خوانا در صفحه بگذار. اگر تصویر باز نشد، متن alt باید به جایش دیده شود.",
         "عمداً مسیر تصویر را غلط کن، صفحه را ببین، بعد مسیر را درست کن تا تصویر برگردد."],
        ["Put an image on the page with a set width, height, and readable alt text. If the image fails, the alt text should stand in for it.",
         "Break the image path on purpose, view the page, then fix the path so the image comes back."],
    ),
    "p2-forms": (
        ["فرم عضویت بساز با نام، رمز، یک گروه رادیویی با name یکسان، و دکمه ارسال.",
         "به فرم یک منوی انتخاب رشته اضافه کن و صفحه را طوری کامل کن که بدون پر کردن نام، فیلد نام خالی ماندنش معلوم باشد."],
        ["Build a signup form with a name, a password, one radio group that shares a name, and a submit button.",
         "Add a field-of-study menu to the form, and mark the name field so an empty name is visible as missing."],
    ),
    "p2-semantic": (
        ["یک صفحه مقاله را با header، main، section و aside بساز و در aside سه پیوند بگذار.",
         "همان محتوا را در صفحه دوم فقط با div تکرار نکن. صفحه دوم را با همان عنصرهای معنایی گسترش بده و یک بخش تازه به main اضافه کن."],
        ["Build an article page with header, main, section, and aside, and put three links in the aside.",
         "Do not rebuild the same content as a page of only div elements. Extend the semantic page with one new block inside main."],
    ),
    "p2-assess-html": (
        ["صفحه پایانی HTML را بساز: عنوان، متن، تصویر، فرم کوتاه، و حداقل دو عنصر معنایی، همه در یک فایل.",
         "همان صفحه را با یک فهرست مطالب بالای صفحه کامل کن که به هر بخش پیوند داخلی داشته باشد."],
        ["Build the finished HTML page in one file: heading, text, image, a short form, and at least two semantic elements.",
         "Finish that page with a contents list at the top that links to each section."],
    ),
    "p2-css-start": (
        ["یک قانون رنگ را یک بار در خود صفحه و یک بار در فایل style.css جدا اعمال کن و صفحه را به فایل خارجی وصل کن.",
         "بالای قانون فایل خارجی یک توضیح CSS بگذار و مطمئن شو آن توضیح روی صفحه دیده نمی‌شود."],
        ["Apply one color rule once inside the page and once in a separate style.css, and connect the page to the external file.",
         "Put a CSS comment above the external rule and check that the comment does not appear on the page."],
    ),
    "p2-css-look": (
        ["چهار انتخاب‌گر عنصر، کلاس، شناسه و گروه را روی یک صفحه واقعی اعمال کن و یک انتخاب‌گر ویژگی برای input لازم اضافه کن.",
         "برای همان صفحه یک تصویر پس‌زمینه بگذار و با اسکرول، چسبیدن یا حرکت پس‌زمینه را در خود صفحه ببین."],
        ["On one real page, apply an element selector, a class, an id, and a group selector, then add an attribute selector for the required inputs.",
         "Give that page a background image and scroll it so you can see whether the background stays fixed or moves."],
    ),
    "p2-box": (
        ["یک جعبه با margin و padding و border متفاوت بساز و متن داخلش را طوری بگذار که فاصله داخل و بیرون در مرورگر دیده شود.",
         "سه دکمه فرم ورود را بساز و هر کدام را با block و inline و inline-block امتحان کن، بعد حالتی را که برای فرم بهتر است نگه دار."],
        ["Build a box with different margin, padding, and border, and put text in it so the inner and outer space is visible in the browser.",
         "Build three login buttons and try block, inline, and inline-block. Keep the display value that works better for the form."],
    ),
    "p2-flex": (
        ["نوار منو را با Flexbox بساز که در عرض کم به خط بعد برود و فاصله بین آیتم‌ها را خود فلکس بدهد.",
         "زیر همان منو سه کارت هم‌عرض بچین و متن یکی را طولانی‌تر کن تا ارتفاع ردیف را در عمل ببینی."],
        ["Build a menu bar with Flexbox that wraps on a narrow width, and let flex set the gap between items.",
         "Under that menu, place three equal cards and make one text longer so you can see the row height."],
    ),
    "p2-flex-work": (
        ["بخش خدمات را با سه کارت بساز که هر کارت تصویر و عنوان دارد و فاصله کارت‌ها فقط از CSS می‌آید.",
         "پس‌زمینه رنگی موقت را از منو بردار و با فاصله، خط یا سایه، ناحیه‌ها را از هم جدا نگه دار."],
        ["Build a services block of three cards. Each card has an image and a title, and the gap comes only from CSS.",
         "Remove the temporary menu background and keep the regions separate with gap, a border, or a shadow."],
    ),
    "p2-media": (
        ["یک مدیا کوئری بنویس که زیر ۶۰۰ پیکسل منوی افقی را عمودی کند. عرض مرورگر را کم کن و نتیجه را ببین.",
         "صفحه را کامل کن تا در عرض کم، کارت‌ها تمام‌عرض شوند و دکمه از صفحه بیرون نزند."],
        ["Write a media query that stacks a horizontal menu vertically below 600 pixels. Narrow the browser and look at the result.",
         "Finish the page so that on a narrow width the cards become full width and the button stays inside the screen."],
    ),
    "p3-intro": (
        ["یک صفحه کوچک بساز که یک دکمه بوت‌استرپ و یک پاراگراف داشته باشد، بعد با چند خط جاوااسکریپت متن پاراگراف را با کلیک عوض کن.",
         "همان صفحه را در نمای باریک هم مرتب کن تا دکمه تمام‌عرض شود."],
        ["Build a small page with one Bootstrap button and a paragraph, then change the paragraph text on click with a few lines of JavaScript.",
         "Also make that page tidy on a narrow screen so the button becomes full width."],
    ),
    "p3-bs-start": (
        ["بوت‌استرپ را به یک صفحه خالی وصل کن و فقط با کلاس آماده یک دکمه و یک جعبه هشدار رنگی نشان بده.",
         "زیر آن‌ها یک کارت ساده با عنوان و متن بساز، بدون نوشتن CSS تازه."],
        ["Connect Bootstrap to an empty page and, using only ready-made classes, show a button and a colored alert.",
         "Under those, build a simple card with a title and text, without writing new CSS."],
    ),
    "p3-bs-util": (
        ["یک کارت بساز و چهار فاصله متفاوت margin و padding را با کلاس بوت‌استرپ روی بخش‌های مختلفش بگذار.",
         "یک فهرست را بدون نشانه بساز و یک تصویر کوچک را دایره‌ای کن."],
        ["Build one card and put four different margin and padding utilities on different parts of it.",
         "Build a list with no bullets and make a small image a circle."],
    ),
    "p3-bs-header": (
        ["سرصفحه فروشگاه را با لوگو، جعبه جستجو و پیوند ورود بساز. در عرض کم، لوگو و ورود را پنهان کن ولی جستجو بماند.",
         "آیتم‌های منوی همان سرصفحه را در محور افقی وسط‌چین کن."],
        ["Build a shop header with a logo, a search box, and a sign-in link. On a narrow width, hide the logo and sign-in, and keep the search.",
         "Center that header's menu items on the horizontal axis."],
    ),
    "p3-bs-grid": (
        ["یک ردیف سه ستونه بساز که در موبایل زیر هم و در صفحه بزرگ کنار هم باشد.",
         "زیر شبکه، یک پاراگراف و یک آیکن را در یک ردیف کنار هم وسط صفحه بگذار."],
        ["Build a row of three columns that stack on a phone and sit side by side on a large screen.",
         "Under the grid, place a paragraph and an icon in one row, centered on the page."],
    ),
    "p3-bs-rwd": (
        ["بلوک تازه‌ترین محصول‌ها را در یک container بساز و تصویر هر محصول را با عرض صفحه جمع و باز کن.",
         "یک نوار پایین مخصوص موبایل بساز که از عرض بزرگ به بالا دیده نشود."],
        ["Build a newest-products block inside a container, and make each product image shrink and grow with the page width.",
         "Build a bottom bar for phones that disappears from the large breakpoint upward."],
    ),
    "p3-bs-nav": (
        ["یک navbar با یک زیرمنو بساز و جمع شدنش را در عرض کم امتحان کن.",
         "صفحه جزئیات محصول را سه ستونه بساز: تصویر، توضیح، قیمت."],
        ["Build a navbar with one dropdown and test how it collapses when the width is small.",
         "Build a product-details page in three columns: image, description, and price."],
    ),
    "p3-bs-form": (
        ["فرم ثبت‌نام را وسط صفحه بساز و حداقل سه کنترل را با کلاس فرم بوت‌استرپ استایل بده.",
         "یک پنجره modal با عنوان، متن و دکمه بستن بساز و آن را با یک دکمه در صفحه باز کن."],
        ["Build the signup form centered on the page and style at least three controls with Bootstrap form classes.",
         "Build a modal with a title, text, and a close button, and open it from a button on the page."],
    ),
    "p3-bs-show": (
        ["یک کاروسل با دو تصویر و دکمه بعدی و قبلی بساز.",
         "پرسش‌های متداول را با آکاردئون سه موردی بساز که باز شدن یکی، بقیه را ببندد."],
        ["Build a carousel with two images and next and previous controls.",
         "Build a three-item FAQ accordion so opening one item closes the others."],
    ),
    "p3-bs-assess": (
        ["یک صفحه واحد بساز که navbar واکنش‌گرا، فرم، modal و carousel را با هم داشته باشد و هر کدام کار کند.",
         "عرض را از موبایل تا دسکتاپ عوض کن و هر جا ستونی از صفحه بیرون زد، همان را در کد درست کن."],
        ["Build one page that contains a working responsive navbar, form, modal, and carousel.",
         "Resize from phone width to desktop and fix any column that spills out of the page."],
    ),
    "p3-js-start": (
        ["یک صفحه بساز که یک جمله را در کنسول چاپ کند و همان جمله را یک بار هم در خود صفحه نشان بدهد.",
         "اسکریپت را یک بار ته body و یک بار در head بگذار و صفحه را طوری تنظیم کن که در هر دو حالت بدون خطای نبودن عنصر کار کند."],
        ["Build a page that prints one sentence in the console and also shows that sentence on the page.",
         "Place the script once at the end of body and once in the head, and arrange the page so both versions run without an error about a missing element."],
    ),
    "p3-js-vars": (
        ["چهار متغیر از نوع‌های مختلف بساز و نوع هر کدام را در صفحه، نه فقط کنسول، نشان بده.",
         "یک قیمت را به صورت رشته بگیر، به عدد تبدیل کن و مبلغ با مالیات را در صفحه چاپ کن."],
        ["Create four variables of different types and show each type on the page, not only in the console.",
         "Read a price as text, convert it to a number, and print the price plus tax on the page."],
    ),
    "p3-js-ops": (
        ["ماشین‌حساب کوچک قیمت بساز: قیمت، تعداد و درصد تخفیف را بگیر و مبلغ نهایی را نشان بده.",
         "به آن یک مقایسه اضافه کن که اگر مبلغ نهایی از ۱۰۰ کمتر بود پیام جدا نشان بدهد."],
        ["Build a small price calculator: read price, quantity, and discount percent, and show the final amount.",
         "Add a comparison that shows a separate message when the final amount is under 100."],
    ),
    "p3-js-data": (
        ["آرایه سه محصول بساز، یکی اضافه کن و همه را در صفحه فهرست کن. بعد یک شیء محصول با نام، قیمت و موجودی بساز و فقط قیمتش را عوض کن.",
         "از همان شیء یک کارت HTML بساز که نام و قیمت را در صفحه نشان بدهد."],
        ["Build an array of three products, add one, and list them all on the page. Then make a product object with name, price, and stock, and change only the price.",
         "From that object, build an HTML card that shows the name and the price on the page."],
    ),
    "p3-js-if": (
        ["وضعیت موجودی را بساز: صفر «ناموجود»، کمتر از ۵ «رو به اتمام»، وگرنه «موجود»، و نتیجه را در یک پاراگراف بگذار.",
         "دکمه خرید را فقط وقتی نشان بده که کاربر وارد شده باشد و موجودی صفر نباشد."],
        ["Build stock status: 0 shows «out of stock», under 5 shows «low», otherwise «in stock», and put the result in a paragraph.",
         "Show the buy button only when the user is signed in and the stock is not zero."],
    ),
    "p3-js-loops": (
        ["جمع قیمت‌های یک آرایه را با حلقه حساب کن و جمع را در صفحه بنویس. قیمت ۰ را در جمع نیاور.",
         "فهرست همان محصول‌ها را با حلقه به صورت آیتم‌های یک ul در صفحه بساز."],
        ["Add the prices in an array with a loop and write the total on the page. Leave a price of 0 out of the total.",
         "Use a loop to build those same products as items in a ul on the page."],
    ),
    "p3-js-func": (
        ["تابعی بساز که قیمت و درصد تخفیف را بگیرد و قیمت نهایی را برگرداند. دو کالا را با آن در صفحه نشان بده.",
         "تابع دوم بساز که نام کالا را با حرف بزرگ اول برگرداند و قیمت را گرد کند، بعد هر دو را داخل یک کارت بگذار."],
        ["Build a function that takes a price and a discount percent and returns the final price. Show two products with it on the page.",
         "Build a second function that returns the product name with a capital first letter and a rounded price, then put both into one card."],
    ),
    "p3-js-dom": (
        ["دکمه‌ای بساز که متن یک پاراگراف را عوض کند. کد باید بعد از ساخته شدن عنصر در صفحه اجرا شود.",
         "فرم دو فیلدی بساز که اگر یکی خالی بود، ارسال انجام نشود و پیام خطا در خود صفحه، زیر همان فیلد، دیده شود."],
        ["Build a button that changes a paragraph's text. The code must run only after the element exists on the page.",
         "Build a two-field form that does not submit when one field is empty, and shows the error on the page under that field."],
    ),
    "p3-js-assess": (
        ["صفحه فیلتر محصول بساز: آرایه کالا، یک ورودی عدد، و دکمه‌ای که فقط کالاهای گران‌تر از آن عدد را نشان بدهد.",
         "به همان صفحه شمارش تعداد نتیجه‌ها را اضافه کن و با هر فیلتر تازه، فهرست قبلی را پاک کن."],
        ["Build a product-filter page: a products array, a number input, and a button that shows only products more expensive than that number.",
         "Add a count of the results to the same page, and clear the previous list on every new filter."],
    ),
    "p4-intro": (
        ["کلاس Book را با سه ویژگی و یک متد نمایش بساز و دو کتاب مختلف از آن بگیر و اطلاعات هر دو را چاپ کن.",
         "به هر کتاب یک متد امانت اضافه کن که وضعیت را از «موجود» به «امانت» عوض کند و دوباره چاپ کند."],
        ["Build a Book class with three attributes and a display method. Create two different books and print both.",
         "Add a borrow method that changes the status from «available» to «on loan» and prints the book again."],
    ),
    "p4-idea": (
        ["برای وسیله آزمایشگاه یک کلاس با سه ویژگی و دو متد بساز و دو شیء واقعی از روی آن بساز.",
         "خروجی برنامه را طوری بنویس که ویژگی‌ها و نتیجه یکی از رفتارها برای هر دو شیء دیده شود."],
        ["Build a class for a piece of lab equipment with three attributes and two methods, and create two real objects from it.",
         "Make the program output show the attributes and the result of one behavior for both objects."],
    ),
    "p4-class": (
        ["کلاس Mobile را با برند، مدل و رنگ بساز، دو گوشی بساز و متد show_info را برای هر دو صدا بزن.",
         "بعد از ساخت شیء، رنگ یکی را عوض کن و show_info را دوباره چاپ کن تا تغییر در خروجی بیاید."],
        ["Build a Mobile class with brand, model, and color. Create two phones and call show_info on both.",
         "After creating an object, change one phone's color and print show_info again so the change appears in the output."],
    ),
    "p4-inherit": (
        ["کلاس Smartphone را از Mobile بساز که ویژگی دوربین دارد. یک شیء بساز و هم متد والد و هم متد take_picture را اجرا کن.",
         "show_info را در فرزند بازنویسی کن تا همان نام متد، جمله دوربین را هم چاپ کند."],
        ["Build a Smartphone class from Mobile that adds a camera attribute. Create one object and run both a parent method and take_picture.",
         "Override show_info in the child so the same method name also prints a camera sentence."],
    ),
    "p4-protect": (
        ["سازنده را طوری بساز که رنگ خالی یا قیمت منفی را قبول نکند و به جای ساخت شیء ناقص، پیام مشخص چاپ کند.",
         "یک ویژگی داخلی برای تعداد تعمیر بساز و فقط از طریق یک متد آن را یکی زیاد کن."],
        ["Build the constructor so it rejects an empty color or a negative price and prints a clear message instead of creating a broken object.",
         "Add an internal repair-count attribute and increase it only through a method."],
    ),
    "p4-assess-oop": (
        ["یک کلاس پایه و یک کلاس فرزند برای وسایل آزمایشگاه بساز و دو شیء را با ویژگی‌ها و یک رفتار چاپ کن.",
         "در همان برنامه یک مقدار نامعتبر را به سازنده بده و به جای قطع بی‌خبر، پیام خطا نشان بده."],
        ["Build a base class and a child class for lab equipment, and print two objects with their attributes and one behavior.",
         "In the same program, pass an invalid value to the constructor and show an error message instead of failing silently."],
    ),
    "p4-files": (
        ["برندها را در brands.txt بنویس، فایل را ببند، دوباره باز کن و خط‌ها را چاپ کن.",
         "برنامه را یک بار با مسیر غلط اجرا کن تا خطا را ببینی، بعد مسیر را درست کن و همان برنامه را موفق اجرا کن."],
        ["Write the brands into brands.txt, close the file, open it again, and print the lines.",
         "Run the program once with a wrong path so you see the error, then fix the path and run the same program successfully."],
    ),
    "p4-errors": (
        ["برنامه تقسیم دو عدد بساز که تقسیم بر صفر و ورودی غیرعددی را با پیام خودت بگیرد و برنامه را ادامه بدهد.",
         "به آن خواندن خط‌های یک فایل را اضافه کن و شماره هر خط را کنار متن چاپ کن."],
        ["Build a divide-two-numbers program that catches division by zero and a non-numeric input with your own message, then keeps running.",
         "Add file-line reading to it and print a line number beside each line of text."],
    ),
    "p4-json": (
        ["لیست گوشی‌ها را در phones.json ذخیره کن، برنامه را ببند، دوباره باز کن و همان داده‌ها را برگردان.",
         "یک فیلد قیمت را در فایل عوض کن و برنامه را طوری بساز که بعد از خواندن، قیمت تازه را چاپ کند. اگر فایل نبود، پیام بده و یک فایل خالی قابل‌استفاده بساز."],
        ["Save a list of phones in phones.json, quit, start again, and load the same data back.",
         "Change one price in the file and make the program print the new price after reading. If the file is missing, show a message and create a usable empty file."],
    ),
    "p4-assess-files": (
        ["برنامه را کامل کن که داده را به JSON تبدیل کند، ذخیره کند، و در اجرای بعدی همان فهرست را برگرداند.",
         "یک فایل JSON خراب کنار برنامه بگذار و با except به‌جای بسته شدن برنامه، پیام «فایل خراب است» نشان بده."],
        ["Finish the program so it converts data to JSON, saves it, and loads the same list on the next run.",
         "Place a broken JSON file beside the program and, with except, show «file is damaged» instead of closing the program."],
    ),
    "p5-intro": (
        ["یک پروژه جنگو خالی بساز و یک صفحه که فقط جمله «آب‌وهوا» را نشان می‌دهد بالا بیاور.",
         "همان صفحه را در قالب HTML جدا ببر تا جمله از فایل قالب بیاید، نه از متن مستقیم داخل view."],
        ["Create an empty Django project and bring up one page that shows only the sentence «Weather».",
         "Move that sentence into a separate HTML template so it comes from the template file, not from text written directly in the view."],
    ),
    "p5-what": (
        ["محیط پروژه را بساز، جنگو را نصب کن و دستوری را اجرا کن که نسخه جنگو و نسخه پایتون را در ترمینال چاپ کند.",
         "پروژه را start کن و صفحه پیش‌فرض جنگو را یک بار در مرورگر باز کن تا مطمئن شوی سرور بالا آمده است."],
        ["Create the project environment, install Django, and run a command that prints the Django version and the Python version in the terminal.",
         "Start the project and open Django's default page once in the browser so you know the server is up."],
    ),
    "p5-project": (
        ["پروژه و اپ آب‌وهوا را بساز، migrate را اجرا کن و یک view بساز که یک جمله ساده را در مرورگر نشان بدهد.",
         "اگر مسیر را از urls حذف کنی صفحه باید ۴۰۴ بدهد. مسیر را برگردان تا همان جمله دوباره دیده شود."],
        ["Create the project and the weather app, run migrate, and build a view that shows one plain sentence in the browser.",
         "Removing the path from urls should make the page 404. Put the path back so the same sentence shows again."],
    ),
    "p5-template": (
        ["نام شهر و دما را از view به قالب بفرست و هر دو را در HTML نشان بده.",
         "فرم کوچکی بساز که عرض و طول جغرافیایی را بگیرد و همان مقدارها را در صفحه نتیجه نشان بدهد. اگر یکی خالی بود، صفحه خطا را خودت بساز."],
        ["Send a city name and a temperature from the view to the template and show both in the HTML.",
         "Build a small form that takes latitude and longitude and shows those values on a result page. If one is empty, build your own error page."],
    ),
    "p5-assess-create": (
        ["از صفر یک صفحه بساز که نام یک شهر را نشان بدهد: پروژه، اپ، view، url و قالب.",
         "دکمه تازه‌سازی را در قالب بگذار که همان صفحه شهر را دوباره بارگذاری کند."],
        ["From nothing, build a page that shows one city name: project, app, view, url, and template.",
         "Put a refresh control in the template that loads the same city page again."],
    ),
    "p5-model": (
        ["مدل City را با نام اجباری بساز، migrate کن و از پنل ادمین دو شهر ثبت کن.",
         "یکی از شهرها را در ادمین ویرایش کن و در فهرست ادمین نتیجه را ببین."],
        ["Build a City model with a required name, migrate, and add two cities in the admin.",
         "Edit one city in the admin and see the result in the admin list."],
    ),
    "p5-list": (
        ["صفحه‌ای بساز که همه شهرهای پایگاه را فهرست کند. اگر شهری نبود، به جای جدول خالی یک جمله نشان بده.",
         "برای هر شهر یک پیوند جزئیات بساز که نام همان شهر را در صفحه جدا نشان بدهد."],
        ["Build a page that lists every city from the database. If there are no cities, show a sentence instead of an empty table.",
         "Give each city a detail link that shows that city's name on its own page."],
    ),
    "p5-auth": (
        ["ورود را بساز تا بعد از ورود کاربر به صفحه اصلی برگردد و دکمه خروج را ببیند. بدون ورود، همان دکمه دیده نشود.",
         "خروج را هم بساز و بعد از خروج، کاربر را به صفحه ورود برگردان."],
        ["Build sign-in so that after signing in the user returns to the home page and sees a sign-out button. Without signing in, that button must not appear.",
         "Also build sign-out, and after sign-out send the user back to the sign-in page."],
    ),
    "p5-crud": (
        ["فرم افزودن شهر را روی خود سایت بساز و یک شهر را بدون پنل ادمین ثبت کن.",
         "کنار هر شهر دکمه حذف بگذار که بعد از حذف، فهرست همان صفحه تازه شود و شهر پاک‌شده دیگر در فهرست نباشد."],
        ["Build the add-city form on the site itself and save one city without using the admin.",
         "Put a delete button beside each city that refreshes the list on the same page, so the deleted city is gone."],
    ),
    "p5-bugs": (
        ["عمداً یک تقسیم بر صفر یا یک شهر بدون نام را در مسیر برنامه بگذار و صفحه را طوری درست کن که به‌جای خطای خام، پیام قابل‌فهم نشان بدهد.",
         "فرم شهر را طوری بساز که نام خالی ذخیره نشود و علامت‌های غیرعادی در نام، صفحه را نشکند."],
        ["Deliberately put a division by zero or a city with no name in the program path, then change the page so it shows an understandable message instead of a raw error.",
         "Build the city form so an empty name is not saved, and unusual characters in the name do not break the page."],
    ),
    "refs": (
        ["یک صفحه resources.html بساز و سه منبع همین فصل را با عنوان و نشانی در آن فهرست کن.",
         "کنار هر منبع یک جمله بساز که بگوید آن منبع را برای کدام پودمان باز می‌کنی، و پیوند را در خود صفحه بگذار."],
        ["Build resources.html and list three sources from this chapter with a title and an address.",
         "Beside each source, put one sentence saying which module you would open it for, and put the link on the page."],
    ),
}
